package com.eleckoi.android.engine.workspace.runtime

import android.content.Context
import com.eleckoi.android.engine.workspace.storage.AtomicWorkspaceFileStore
import com.eleckoi.android.foundation.serialization.ElecKoiJson
import java.io.File
import java.math.BigDecimal
import java.math.RoundingMode
import java.nio.file.Files
import java.nio.file.LinkOption
import kotlinx.serialization.Serializable
import kotlinx.serialization.decodeFromString

/**
 * Installs APK-bundled DSH plugins outside the immutable Runtime and composes the active Cordis
 * configuration in the persistent DSH home. Marketplace installers can use the same manifest and
 * registry layout without rebuilding either the DSH executable or its `.egruntime` bundle.
 */
internal class DeepSeekPluginCompositionManager(
    private val assetReader: (String) -> ByteArray,
    private val atomicFiles: AtomicWorkspaceFileStore = AtomicWorkspaceFileStore(),
) {
    constructor(context: Context) : this(
        assetReader = { path -> context.assets.open(path).use { it.readBytes() } },
    )

    fun prepare(
        packagedConfig: File,
        deepSeekHome: File,
        modelContextWindow: Int? = null,
        autoCompactTokenLimit: Int? = null,
    ): File {
        val sourceConfig = requireRegularFile(packagedConfig, "DSH 基础配置不存在")
        require(sourceConfig.length() in 1..MaxConfigBytes) { "DSH 基础配置大小无效" }

        val appRoot = ownedDirectory(deepSeekHome, AppDirectory)
        val pluginsRoot = ownedDirectory(appRoot, PluginsDirectory)
        val bundledSelections = BundledPlugins.map { bundle ->
            installBundledPlugin(bundle, pluginsRoot)
        }
        val externalSelections = readRegistry(appRoot).enabled
        val selections = linkedMapOf<String, DeepSeekPluginSelection>()
        (bundledSelections + externalSelections).forEach { selection ->
            require(selections.put(selection.id, selection) == null) {
                "DSH 插件重复启用：${selection.id}"
            }
        }

        val manifests = selections.values.map { selection ->
            loadInstalledPlugin(pluginsRoot, selection)
        }
        copyRuntimeCompanions(requireNotNull(sourceConfig.parentFile), appRoot)
        val activeConfig = safeFile(appRoot, ActiveConfigFilename)
        val base = removeLegacyResponsesAdapter(
            synchronizeRuntimeContextPolicy(
                applyCompactionPolicy(
                    source = sourceConfig.readText(Charsets.UTF_8).trimEnd(),
                    modelContextWindow = modelContextWindow,
                    autoCompactTokenLimit = autoCompactTokenLimit,
                ),
            ),
        )
        val pluginRows = manifests.joinToString("\n\n") { manifest ->
            val relativeConfig = "$PluginsDirectory/${manifest.id}/${manifest.version}/${manifest.cordisConfig}"
            """
                - id: eleckoi-installed-plugin-${manifest.id}
                  name: cordis:include
                  config:
                    path: ./$relativeConfig
            """.trimIndent()
        }
        val composed = buildString {
            appendLine("# Generated by ElecKoi. Install or enable plugins through the App; do not edit this file.")
            append(base)
            append('\n')
            if (pluginRows.isNotEmpty()) {
                appendLine()
                appendLine("# App-managed external DSH plugins.")
                append(pluginRows)
                append('\n')
            }
        }
        require(composed.toByteArray(Charsets.UTF_8).size <= MaxComposedConfigBytes) {
            "启用的 DSH 插件配置过大"
        }
        writeIfChanged(activeConfig, composed.toByteArray(Charsets.UTF_8))
        return activeConfig
    }

    private fun applyCompactionPolicy(
        source: String,
        modelContextWindow: Int?,
        autoCompactTokenLimit: Int?,
    ): String {
        if (autoCompactTokenLimit == null) return source
        val contextWindow = requireNotNull(modelContextWindow) {
            "自动压缩阈值缺少模型上下文窗口"
        }
        require(contextWindow > 0 && autoCompactTokenLimit in 1..contextWindow) {
            "自动压缩阈值必须小于或等于模型上下文窗口"
        }

        val lines = source.lines().toMutableList()
        val blockStart = lines.indexOfFirst { it.trim() == "- id: compaction-basic" }
        require(blockStart >= 0) { "DSH 基础配置缺少 compaction-basic" }
        val blockIndent = lines[blockStart].indexOfFirst { !it.isWhitespace() }.coerceAtLeast(0)
        val blockEnd = ((blockStart + 1) until lines.size).firstOrNull { index ->
            val line = lines[index]
            line.isNotBlank() &&
                line.indexOfFirst { !it.isWhitespace() } == blockIndent &&
                line.trimStart().startsWith("- id:")
        } ?: lines.size

        fun settingIndex(name: String): Int? = (blockStart until blockEnd)
            .filter { lines[it].trimStart().startsWith("$name:") }
            .also { require(it.size <= 1) { "DSH compaction-basic 重复配置 $name" } }
            .singleOrNull()

        val thresholdIndex = requireNotNull(settingIndex("thresholdRatio")) {
            "DSH compaction-basic 缺少 thresholdRatio"
        }
        val retainRatioIndex = settingIndex("retainRatio")
        val retainTokensIndex = settingIndex("retainTokens")
        require((retainRatioIndex != null) xor (retainTokensIndex != null)) {
            "DSH compaction-basic 必须且只能配置一种保留预算"
        }
        val maxTokensIndex = requireNotNull(settingIndex("maxTokens")) {
            "DSH compaction-basic 缺少 maxTokens"
        }

        val thresholdRatio = BigDecimal(autoCompactTokenLimit)
            .divide(BigDecimal(contextWindow), 12, RoundingMode.HALF_UP)
            .stripTrailingZeros()
            .toPlainString()
        fun replaceValue(index: Int, name: String, value: Any) {
            val indentation = lines[index].takeWhile(Char::isWhitespace)
            lines[index] = "$indentation$name: $value"
        }
        replaceValue(thresholdIndex, "thresholdRatio", thresholdRatio)
        // An absolute trigger threshold says nothing about how much recent history the user
        // wants retained. Do not derive a second policy from it. Zero delegates the cutoff to
        // DSH's native balanced-range selector, which still keeps the newest indivisible unit.
        replaceValue(retainRatioIndex ?: requireNotNull(retainTokensIndex), "retainTokens", 0)
        // The summary completion has its own output budget. Scaling it down with the trigger
        // threshold can leave reasoning models no visible text budget at low test thresholds.
        replaceValue(maxTokensIndex, "maxTokens", DefaultCompactionSummaryMaxTokens)
        return lines.joinToString("\n")
    }

    /**
     * `workspaceContext: false` is ElecKoi's complete prompt-compatibility mode. Keep DSH's
     * dynamic runtime snapshots in lockstep so sandbox and approval policy text cannot appear as
     * an additional, invisible user message after workspace context has been disabled.
     */
    private fun synchronizeRuntimeContextPolicy(source: String): String {
        val lines = source.lines().toMutableList()
        val blockStart = lines.indexOfFirst { it.trim() == "- id: agent-spine" }
        if (blockStart < 0) return source
        val blockIndent = lines[blockStart].indexOfFirst { !it.isWhitespace() }.coerceAtLeast(0)
        val blockEnd = ((blockStart + 1) until lines.size).firstOrNull { index ->
            val line = lines[index]
            line.isNotBlank() &&
                line.indexOfFirst { !it.isWhitespace() } == blockIndent &&
                line.trimStart().startsWith("- id:")
        } ?: lines.size
        val workspaceRows = (blockStart until blockEnd)
            .filter { lines[it].trim() == "workspaceContext: false" }
        if (workspaceRows.isEmpty()) return source
        require(workspaceRows.size == 1) { "DSH agent-spine 重复配置 workspaceContext" }

        val runtimeRows = (blockStart until blockEnd)
            .filter { lines[it].trimStart().startsWith("includeRuntimeContext:") }
        require(runtimeRows.size <= 1) { "DSH agent-spine 重复配置 includeRuntimeContext" }
        if (runtimeRows.isNotEmpty()) {
            val index = runtimeRows.single()
            val indentation = lines[index].takeWhile(Char::isWhitespace)
            lines[index] = "${indentation}includeRuntimeContext: false"
        } else {
            val workspaceIndex = workspaceRows.single()
            val indentation = lines[workspaceIndex].takeWhile(Char::isWhitespace)
            lines.add(workspaceIndex, "${indentation}includeRuntimeContext: false")
        }
        return lines.joinToString("\n")
    }

    /** The APK bridge is the only production provider route; Git preserves the former profile. */
    private fun removeLegacyResponsesAdapter(source: String): String {
        val lines = source.lines().toMutableList()
        val blockStart = lines.indexOfFirst { it.trim() == "- id: llm" }
        if (blockStart < 0) return source
        val blockIndent = lines[blockStart].indexOfFirst { !it.isWhitespace() }.coerceAtLeast(0)
        val blockEnd = ((blockStart + 1) until lines.size).firstOrNull { index ->
            val line = lines[index]
            line.isNotBlank() &&
                line.indexOfFirst { !it.isWhitespace() } == blockIndent &&
                line.trimStart().startsWith("- id:")
        } ?: lines.size
        val block = lines.subList(blockStart, blockEnd)
        if (block.none { it.trim() == "name: '@deepseek-ai/dsh-llm-pi-ai'" }) return source
        block.clear()
        while (blockStart < lines.size && lines[blockStart].isBlank()) lines.removeAt(blockStart)
        return lines.joinToString("\n").trimEnd()
    }

    private fun installBundledPlugin(
        bundle: BundledPlugin,
        pluginsRoot: File,
    ): DeepSeekPluginSelection {
        val manifestBytes = readAsset("${bundle.assetRoot}/$ManifestFilename")
        val manifest = parseManifest(manifestBytes.toString(Charsets.UTF_8), "APK 插件 ${bundle.assetRoot}")
        require(manifest.id == bundle.expectedId) { "APK 插件编号与清单不一致：${bundle.assetRoot}" }
        val versionRoot = ownedDirectory(ownedDirectory(pluginsRoot, manifest.id), manifest.version)
        writeIfChanged(safeFile(versionRoot, ManifestFilename), manifestBytes)
        manifest.files.forEach { relative ->
            val bytes = readAsset("${bundle.assetRoot}/$relative")
            writeIfChanged(safeFile(versionRoot, relative), bytes)
        }
        return DeepSeekPluginSelection(manifest.id, manifest.version)
    }

    private fun loadInstalledPlugin(
        pluginsRoot: File,
        selection: DeepSeekPluginSelection,
    ): DeepSeekPluginManifest {
        validatePluginId(selection.id)
        validatePluginVersion(selection.version)
        val versionRoot = existingOwnedDirectory(
            existingOwnedDirectory(pluginsRoot, selection.id),
            selection.version,
        )
        val manifestFile = requireRegularFile(
            safeFile(versionRoot, ManifestFilename),
            "DSH 插件缺少清单：${selection.id}@${selection.version}",
        )
        require(manifestFile.length() in 1..MaxManifestBytes) {
            "DSH 插件清单大小无效：${selection.id}@${selection.version}"
        }
        val manifest = parseManifest(
            manifestFile.readText(Charsets.UTF_8),
            "DSH 插件 ${selection.id}@${selection.version}",
        )
        require(manifest.id == selection.id && manifest.version == selection.version) {
            "DSH 插件目录与清单身份不一致：${selection.id}@${selection.version}"
        }
        manifest.files.forEach { relative ->
            requireRegularFile(
                safeFile(versionRoot, relative),
                "DSH 插件文件缺失：${manifest.id}@${manifest.version}/$relative",
            )
        }
        requireRegularFile(
            safeFile(versionRoot, manifest.cordisConfig),
            "DSH 插件缺少 Cordis 配置：${manifest.id}@${manifest.version}",
        )
        return manifest
    }

    private fun readRegistry(appRoot: File): DeepSeekPluginRegistry {
        val file = safeFile(appRoot, RegistryFilename)
        if (!file.exists()) return DeepSeekPluginRegistry()
        requireRegularFile(file, "DSH 插件启用清单不安全")
        require(file.length() in 1..MaxRegistryBytes) { "DSH 插件启用清单大小无效" }
        val registry = runCatching {
            ElecKoiJson.decodeFromString<DeepSeekPluginRegistry>(file.readText(Charsets.UTF_8))
        }.getOrElse { error -> throw IllegalArgumentException("DSH 插件启用清单无效", error) }
        require(registry.schemaVersion == PluginSchemaVersion) { "不支持的 DSH 插件启用清单版本" }
        require(registry.enabled.size <= MaxEnabledPlugins) { "启用的 DSH 插件数量过多" }
        return registry
    }

    private fun parseManifest(text: String, label: String): DeepSeekPluginManifest {
        val manifest = runCatching {
            ElecKoiJson.decodeFromString<DeepSeekPluginManifest>(text)
        }.getOrElse { error -> throw IllegalArgumentException("$label 清单无效", error) }
        require(manifest.schemaVersion == PluginSchemaVersion) { "$label 使用了不支持的清单版本" }
        validatePluginId(manifest.id)
        validatePluginVersion(manifest.version)
        require(manifest.files.isNotEmpty() && manifest.files.size <= MaxFilesPerPlugin) {
            "$label 文件列表无效"
        }
        require(manifest.files.distinct().size == manifest.files.size) { "$label 包含重复文件" }
        manifest.files.forEach(::validateRelativePath)
        validateRelativePath(manifest.cordisConfig)
        require(manifest.cordisConfig in manifest.files) { "$label 未声明 Cordis 配置文件" }
        return manifest
    }

    private fun copyRuntimeCompanions(sourceDirectory: File, appRoot: File) {
        sourceDirectory.listFiles().orEmpty()
            .filter { source ->
                source.name != ActiveConfigFilename &&
                    Files.isRegularFile(source.toPath(), LinkOption.NOFOLLOW_LINKS)
            }
            .forEach { source ->
                require(source.length() in 1..MaxRuntimeCompanionBytes) {
                    "DSH Runtime 配置附件大小无效：${source.name}"
                }
                writeIfChanged(safeFile(appRoot, source.name), source.readBytes())
            }
    }

    private fun readAsset(path: String): ByteArray {
        val bytes = assetReader(path)
        require(bytes.isNotEmpty() && bytes.size <= MaxBundledAssetBytes) { "APK 插件资源大小无效：$path" }
        return bytes
    }

    private fun writeIfChanged(target: File, bytes: ByteArray) {
        if (
            Files.isRegularFile(target.toPath(), LinkOption.NOFOLLOW_LINKS) &&
            target.length() == bytes.size.toLong() &&
            target.readBytes().contentEquals(bytes)
        ) {
            return
        }
        require(!Files.isSymbolicLink(target.toPath())) { "DSH 插件目标文件不安全：${target.name}" }
        atomicFiles.writeBytes(target, bytes)
    }

    private fun ownedDirectory(parent: File, name: String): File {
        validatePathSegment(name)
        val canonicalParent = parent.canonicalFile
        require(canonicalParent.isDirectory || canonicalParent.mkdirs()) { "无法创建 DSH 插件父目录" }
        require(!Files.isSymbolicLink(canonicalParent.toPath())) { "DSH 插件父目录不安全" }
        val target = File(canonicalParent, name)
        if (!target.exists()) require(target.mkdir()) { "无法创建 DSH 插件目录：$name" }
        return existingOwnedDirectory(canonicalParent, name)
    }

    private fun existingOwnedDirectory(parent: File, name: String): File {
        validatePathSegment(name)
        val canonicalParent = parent.canonicalFile
        val unresolved = File(canonicalParent, name)
        require(
            Files.isDirectory(unresolved.toPath(), LinkOption.NOFOLLOW_LINKS) &&
                !Files.isSymbolicLink(unresolved.toPath()),
        ) { "DSH 插件目录不存在或不安全：$name" }
        val target = unresolved.canonicalFile
        require(target.parentFile == canonicalParent) { "DSH 插件目录越界：$name" }
        return target
    }

    private fun safeFile(root: File, relative: String): File {
        validateRelativePath(relative)
        val canonicalRoot = root.canonicalFile
        var parent = canonicalRoot
        val segments = relative.split('/')
        segments.dropLast(1).forEach { segment -> parent = ownedDirectory(parent, segment) }
        val target = File(parent, segments.last())
        require(target.canonicalFile.toPath().startsWith(canonicalRoot.toPath())) {
            "DSH 插件文件路径越界：$relative"
        }
        return target
    }

    private fun validatePluginId(value: String) {
        require(PluginId.matches(value)) { "DSH 插件编号无效：$value" }
    }

    private fun validatePluginVersion(value: String) {
        require(PluginVersion.matches(value)) { "DSH 插件版本无效：$value" }
    }

    private fun validateRelativePath(value: String) {
        require(
            value.isNotBlank() && value.length <= MaxRelativePathChars &&
                !value.startsWith('/') && '\\' !in value &&
                value.split('/').all { segment -> PathSegment.matches(segment) },
        ) { "DSH 插件相对路径无效：$value" }
    }

    private fun validatePathSegment(value: String) {
        require(PathSegment.matches(value)) { "DSH 插件路径段无效：$value" }
    }

    private fun requireRegularFile(file: File, message: String): File {
        require(
            Files.isRegularFile(file.toPath(), LinkOption.NOFOLLOW_LINKS) &&
                !Files.isSymbolicLink(file.toPath()),
        ) { message }
        return file.canonicalFile
    }

    private data class BundledPlugin(
        val expectedId: String,
        val assetRoot: String,
    )

    private companion object {
        const val PluginSchemaVersion = 1
        const val AppDirectory = "eleckoi"
        const val PluginsDirectory = "plugins"
        const val ManifestFilename = "manifest.json"
        const val RegistryFilename = "enabled-plugins.json"
        const val ActiveConfigFilename = "cordis.yml"
        const val MaxManifestBytes = 64L * 1024L
        const val MaxRegistryBytes = 256L * 1024L
        const val MaxConfigBytes = 2L * 1024L * 1024L
        const val MaxComposedConfigBytes = 4 * 1024 * 1024
        const val MaxRuntimeCompanionBytes = 4L * 1024L * 1024L
        const val MaxBundledAssetBytes = 4 * 1024 * 1024
        const val MaxFilesPerPlugin = 64
        const val MaxEnabledPlugins = 128
        const val MaxRelativePathChars = 240
        const val DefaultCompactionSummaryMaxTokens = 8_192
        val PluginId = Regex("^[a-z0-9][a-z0-9._-]{0,79}$")
        val PluginVersion = Regex("^[A-Za-z0-9][A-Za-z0-9._+-]{0,79}$")
        val PathSegment = Regex("^[A-Za-z0-9][A-Za-z0-9._+-]{0,119}$")
        val BundledPlugins = listOf(
            BundledPlugin(
                expectedId = "eleckoi-provider-bridge",
                assetRoot = "dsh-plugins/provider-bridge",
            ),
            BundledPlugin(
                expectedId = "eleckoi-context-pressure",
                assetRoot = "dsh-plugins/context-pressure",
            ),
        )
    }
}

@Serializable
internal data class DeepSeekPluginManifest(
    val schemaVersion: Int,
    val id: String,
    val version: String,
    val cordisConfig: String,
    val files: List<String>,
)

@Serializable
internal data class DeepSeekPluginRegistry(
    val schemaVersion: Int = 1,
    val enabled: List<DeepSeekPluginSelection> = emptyList(),
)

@Serializable
internal data class DeepSeekPluginSelection(
    val id: String,
    val version: String,
)
