package com.eleckoi.android.feature.characters.modes.story.regex.data

import com.eleckoi.android.feature.characters.modes.story.regex.model.RegexRule
import com.eleckoi.android.feature.characters.modes.story.regex.model.RegexRuleTarget

object RegexRuleProcessor {
    fun transform(
        text: String,
        rules: List<RegexRule>,
        target: RegexRuleTarget,
        replacementDecorator: (String) -> String = { it },
        protectDecoratedReplacements: Boolean = false,
    ): String {
        if (text.isEmpty()) return text
        val protected = if (protectDecoratedReplacements) mutableListOf<String>() else null
        val transformed = rules
            .asSequence()
            .filter { it.enabled && target in it.targets && it.pattern.isNotBlank() }
            // The caller's sequence also carries scope priority. Every scope restarts its local
            // order at zero, so sorting the combined sequence here would interleave scopes and let
            // a later rule scan frontend source generated by an earlier scope.
            .fold(text) { current, rule ->
                apply(
                    text = current,
                    rule = rule,
                    replacementDecorator = { replacement ->
                        val decorated = replacementDecorator(replacement)
                        if (protected != null && decorated != replacement) {
                            val index = protected.size
                            protected += decorated
                            protectedReplacementToken(index)
                        } else {
                            decorated
                        }
                    },
                )
            }
        return protected?.let { restoreProtectedReplacements(transformed, it) } ?: transformed
    }

    fun validationMessage(rule: RegexRule): String? = runCatching { compile(rule) }.exceptionOrNull()
        ?.message
        ?.takeIf(String::isNotBlank)

    private fun apply(
        text: String,
        rule: RegexRule,
        replacementDecorator: (String) -> String,
    ): String {
        val parsed = runCatching { parseDelimitedPattern(rule.pattern) }.getOrNull() ?: return text
        val expression = runCatching { compile(rule, parsed) }.getOrNull() ?: return text
        val replacement: (MatchResult) -> CharSequence = { match ->
            replacementDecorator(replacementFor(match, rule.replacement))
        }
        return if ('g' in parsed.flags) {
            expression.replace(text, replacement)
        } else {
            expression.find(text)?.let { match ->
                text.replaceRange(match.range, replacement(match).toString())
            } ?: text
        }
    }

    private fun compile(rule: RegexRule): Regex = compile(rule, parseDelimitedPattern(rule.pattern))

    private fun compile(rule: RegexRule, parsed: ParsedPattern): Regex {
        val unsupportedFlags = parsed.flags.filterNot { it in "gims" }.toSet()
        require(unsupportedFlags.isEmpty()) {
            "不支持的正则标志：${unsupportedFlags.joinToString("")}"
        }
        val options = buildSet {
            if ('i' in parsed.flags) add(RegexOption.IGNORE_CASE)
            if ('m' in parsed.flags) add(RegexOption.MULTILINE)
            if ('s' in parsed.flags) add(RegexOption.DOT_MATCHES_ALL)
        }
        val key = CompiledPatternKey(parsed.body, options)
        return synchronized(compiledExpressions) {
            compiledExpressions[key] ?: Regex(parsed.body, options).also { expression ->
                compiledExpressions[key] = expression
            }
        }
    }

    private fun protectedReplacementToken(index: Int): String =
        "$ProtectedReplacementPrefix$index$ProtectedReplacementSuffix"

    private fun restoreProtectedReplacements(text: String, replacements: List<String>): String {
        if (replacements.isEmpty()) return text
        return ProtectedReplacementToken.replace(text) { match ->
            match.groupValues[1].toIntOrNull()
                ?.let(replacements::getOrNull)
                ?: match.value
        }
    }

    private fun replacementFor(match: MatchResult, source: String): String {
        val output = StringBuilder()
        var index = 0
        while (index < source.length) {
            val char = source[index]
            if (char != '$' || index == source.lastIndex) {
                output.append(char)
                index += 1
                continue
            }
            when (source[index + 1]) {
                '$' -> {
                    output.append('$')
                    index += 2
                }
                '&' -> {
                    output.append(match.value)
                    index += 2
                }
                '<' -> {
                    val end = source.indexOf('>', index + 2)
                    if (end == -1) {
                        output.append('$')
                        index += 1
                    } else {
                        val name = source.substring(index + 2, end)
                        output.append(runCatching { match.groups[name]?.value }.getOrNull().orEmpty())
                        index = end + 1
                    }
                }
                else -> {
                    val end = source.indexOfFirstFrom(index + 1) { !it.isDigit() }
                    if (end == index + 1) {
                        output.append('$')
                        index += 1
                    } else {
                        val groupIndex = source.substring(index + 1, end).toIntOrNull()
                        output.append(groupIndex?.let { match.groups[it]?.value }.orEmpty())
                        index = end
                    }
                }
            }
        }
        return output.toString().replace("{{match}}", match.value, ignoreCase = true)
    }

    private fun String.indexOfFirstFrom(startIndex: Int, predicate: (Char) -> Boolean): Int {
        for (index in startIndex until length) if (predicate(this[index])) return index
        return length
    }

    private fun parseDelimitedPattern(pattern: String): ParsedPattern {
        val trimmed = pattern.trim()
        if (trimmed.length >= 3 && trimmed.first() == '/') {
            val closing = trimmed.lastIndexOf('/')
            if (closing > 0) return ParsedPattern(trimmed.substring(1, closing), trimmed.substring(closing + 1))
        }
        return ParsedPattern(trimmed, "")
    }

    private data class ParsedPattern(val body: String, val flags: String)

    private data class CompiledPatternKey(
        val body: String,
        val options: Set<RegexOption>,
    )

    private val compiledExpressions = object : LinkedHashMap<CompiledPatternKey, Regex>(
        MaxCompiledPatterns,
        0.75f,
        true,
    ) {
        override fun removeEldestEntry(
            eldest: MutableMap.MutableEntry<CompiledPatternKey, Regex>?,
        ): Boolean = size > MaxCompiledPatterns
    }

    private const val MaxCompiledPatterns = 128
    private const val ProtectedReplacementPrefix = "\uE000eleckoi-regex:"
    private const val ProtectedReplacementSuffix = ":\uE001"
    private val ProtectedReplacementToken = Regex(
        Regex.escape(ProtectedReplacementPrefix) + "(\\d+)" + Regex.escape(ProtectedReplacementSuffix),
    )
}
