// Generated by scripts/generate-common-schema.mjs. Edit the canonical SQL snapshot, then regenerate.

import { sql } from 'drizzle-orm'
import { integer, real, text, primaryKey, sqliteTable } from 'drizzle-orm/sqlite-core'

export const chatSessions = sqliteTable('chat_sessions', {
  id: text('id').notNull().primaryKey(),
  workspaceId: text('workspaceId').notNull(),
  title: text('title').notNull(),
  characterId: text('characterId').notNull(),
  characterName: text('characterName').notNull(),
  characterAvatar: text('characterAvatar').notNull(),
  characterMode: text('characterMode').notNull(),
  permissionMode: text('permissionMode').notNull(),
  historySummary: text('historySummary').notNull(),
  historyMessageCount: integer('historyMessageCount').notNull(),
  historyUserMessageCount: integer('historyUserMessageCount').notNull(),
  createdAt: text('createdAt').notNull(),
  updatedAt: text('updatedAt').notNull(),
})

export const chatSessionCharacterSnapshots = sqliteTable('chat_session_character_snapshots', {
  sessionId: text('sessionId').notNull().primaryKey(),
  personaJson: text('personaJson').notNull(),
})

export const chatSessionModelSettings = sqliteTable('chat_session_model_settings', {
  sessionId: text('sessionId').notNull().primaryKey(),
  settingsJson: text('settingsJson').notNull(),
})

export const chatSessionVariableStates = sqliteTable('chat_session_variable_states', {
  sessionId: text('sessionId').notNull(),
  kind: text('kind').notNull(),
  stateJson: text('stateJson').notNull(),
}, (table) => [primaryKey({ columns: [table.sessionId, table.kind] })])

export const characters = sqliteTable('characters', {
  id: text('id').notNull().primaryKey(),
  name: text('name').notNull(),
  avatar: text('avatar').notNull(),
  squareImage: text('squareImage').notNull(),
  coverImage: text('coverImage').notNull(),
  groupName: text('groupName').notNull(),
  orderIndex: integer('orderIndex').notNull(),
  groupViewOrder: integer('groupViewOrder').notNull(),
  folder: text('folder').notNull(),
  characterMode: text('characterMode').notNull(),
  frontendBeautyEnabled: integer('frontendBeautyEnabled').notNull(),
  assistantName: text('assistantName').notNull(),
  assistantAvatar: text('assistantAvatar').notNull(),
  profileAge: text('profileAge').notNull(),
  profileSex: text('profileSex').notNull(),
  profileHeight: text('profileHeight').notNull(),
  profileBirthday: text('profileBirthday').notNull(),
  profileLike: text('profileLike').notNull(),
  showOpening: integer('showOpening').notNull(),
  chatBackground: text('chatBackground').notNull(),
  chatBackgroundOpacity: real('chatBackgroundOpacity').notNull(),
  chatBackgroundBlur: real('chatBackgroundBlur').notNull(),
  chatBackgroundScrim: real('chatBackgroundScrim').notNull(),
})

export const characterTextContents = sqliteTable('character_text_contents', {
  characterId: text('characterId').notNull(),
  kind: text('kind').notNull(),
  content: text('content').notNull(),
}, (table) => [primaryKey({ columns: [table.characterId, table.kind] })])

export const characterMeta = sqliteTable('character_meta', {
  id: text('id').notNull().primaryKey(),
  activeCharacterId: text('activeCharacterId').notNull(),
  groupsJson: text('groupsJson').notNull(),
  listAllExpanded: integer('listAllExpanded').notNull(),
  expandedGroupNamesJson: text('expandedGroupNamesJson').notNull(),
})

export const userProfile = sqliteTable('user_profile', {
  id: text('id').notNull().primaryKey(),
  userName: text('userName').notNull(),
  userAvatar: text('userAvatar').notNull(),
  userSquare: text('userSquare').notNull(),
  userPortrait: text('userPortrait').notNull(),
  userCover: text('userCover').notNull(),
})

export const modelConfigs = sqliteTable('model_configs', {
  id: text('id').notNull().primaryKey(),
  name: text('name').notNull(),
  provider: text('provider').notNull(),
  apiKey: text('apiKey').notNull(),
  baseUrl: text('baseUrl').notNull(),
  proxyUrl: text('proxyUrl').notNull(),
  model: text('model').notNull(),
  modelOptionsJson: text('modelOptionsJson').notNull(),
  customHeadersJson: text('customHeadersJson').notNull(),
  supportsTools: integer('supportsTools'),
  enabled: integer('enabled').notNull(),
  imageSettingsJson: text('imageSettingsJson').notNull(),
  apiFormat: text('apiFormat').notNull(),
})

export const modelConfigMeta = sqliteTable('model_config_meta', {
  id: text('id').notNull().primaryKey(),
  activeConfigId: text('activeConfigId').notNull(),
})

export const variableConfigs = sqliteTable('variable_configs', {
  characterId: text('characterId').notNull().primaryKey(),
  activeVersionId: text('activeVersionId').notNull(),
  updatedAt: text('updatedAt').notNull(),
  revision: integer('revision').notNull(),
})

export const variableConfigVersions = sqliteTable('variable_config_versions', {
  characterId: text('characterId').notNull(),
  versionId: text('versionId').notNull(),
  sortIndex: integer('sortIndex').notNull(),
  name: text('name').notNull(),
  expandedObjectIdsJson: text('expandedObjectIdsJson').notNull(),
  createdAt: text('createdAt').notNull(),
  updatedAt: text('updatedAt').notNull(),
}, (table) => [primaryKey({ columns: [table.characterId, table.versionId] })])

export const variableConfigVersionContents = sqliteTable('variable_config_version_contents', {
  characterId: text('characterId').notNull(),
  versionId: text('versionId').notNull(),
  kind: text('kind').notNull(),
  content: text('content').notNull(),
}, (table) => [primaryKey({ columns: [table.characterId, table.versionId, table.kind] })])

export const variableConfigObjects = sqliteTable('variable_config_objects', {
  characterId: text('characterId').notNull(),
  versionId: text('versionId').notNull(),
  objectId: text('objectId').notNull(),
  sortIndex: integer('sortIndex').notNull(),
  payloadJson: text('payloadJson').notNull(),
}, (table) => [primaryKey({ columns: [table.characterId, table.versionId, table.objectId] })])

export const variableConfigVariables = sqliteTable('variable_config_variables', {
  characterId: text('characterId').notNull(),
  versionId: text('versionId').notNull(),
  variableId: text('variableId').notNull(),
  sortIndex: integer('sortIndex').notNull(),
  payloadJson: text('payloadJson').notNull(),
}, (table) => [primaryKey({ columns: [table.characterId, table.versionId, table.variableId] })])

export const globalRegexRules = sqliteTable('global_regex_rules', {
  id: text('id').notNull().primaryKey(),
  name: text('name').notNull(),
  pattern: text('pattern').notNull(),
  replacement: text('replacement').notNull(),
  targetsJson: text('targetsJson').notNull(),
  enabled: integer('enabled').notNull(),
  displayOnly: integer('displayOnly').notNull(),
  promptOnly: integer('promptOnly').notNull(),
  runOnEdit: integer('runOnEdit').notNull(),
  sortIndex: integer('sortIndex').notNull(),
})

export const characterRegexRules = sqliteTable('character_regex_rules', {
  characterId: text('characterId').notNull(),
  id: text('id').notNull(),
  name: text('name').notNull(),
  pattern: text('pattern').notNull(),
  replacement: text('replacement').notNull(),
  targetsJson: text('targetsJson').notNull(),
  enabled: integer('enabled').notNull(),
  displayOnly: integer('displayOnly').notNull(),
  promptOnly: integer('promptOnly').notNull(),
  runOnEdit: integer('runOnEdit').notNull(),
  sortIndex: integer('sortIndex').notNull(),
}, (table) => [primaryKey({ columns: [table.characterId, table.id] })])

export const regexEnablementVersions = sqliteTable('regex_enablement_versions', {
  id: text('id').notNull().primaryKey(),
  name: text('name').notNull(),
  sortIndex: integer('sortIndex').notNull(),
  globalEnabledIdsJson: text('globalEnabledIdsJson').notNull(),
  characterEnabledIdsJson: text('characterEnabledIdsJson').notNull(),
  agentPresetEnabledIdsJson: text('agentPresetEnabledIdsJson').notNull().default(sql.raw("'[]'")),
})

export const regexState = sqliteTable('regex_state', {
  singletonId: integer('singletonId').notNull().primaryKey(),
  activeVersionId: text('activeVersionId'),
  revision: integer('revision').notNull(),
})

export const globalToolConfig = sqliteTable('global_tool_config', {
  singletonId: integer('singletonId').notNull().primaryKey(),
  payloadJson: text('payloadJson').notNull(),
  updatedAt: text('updatedAt').notNull(),
})

export const frontendProjects = sqliteTable('frontend_projects', {
  id: text('id').notNull().primaryKey(),
  characterId: text('characterId').notNull(),
  name: text('name').notNull(),
  entryFile: text('entryFile').notNull(),
  filesJson: text('filesJson').notNull(),
  importedAt: text('importedAt').notNull(),
})

export const characterFrontendSettings = sqliteTable('character_frontend_settings', {
  characterId: text('characterId').notNull().primaryKey(),
  selectedProjectId: text('selectedProjectId'),
  messageRendererEnabled: integer('messageRendererEnabled').notNull(),
})

export const cleanupOperations = sqliteTable('cleanup_operations', {
  id: text('id').notNull().primaryKey(),
  kind: text('kind').notNull(),
  targetId: text('targetId').notNull(),
  state: text('state').notNull(),
  attemptCount: integer('attemptCount').notNull(),
  createdAtEpochMs: integer('createdAtEpochMs').notNull(),
  updatedAtEpochMs: integer('updatedAtEpochMs').notNull(),
  lastError: text('lastError').notNull(),
})

export const agentConversations = sqliteTable('agent_conversations', {
  id: text('id').notNull().primaryKey(),
  surface: text('surface').notNull(),
  activeBranchId: text('activeBranchId').notNull(),
  createdAt: text('createdAt').notNull(),
  updatedAt: text('updatedAt').notNull(),
  revision: integer('revision').notNull(),
})

export const agentConversationDisplayCache = sqliteTable('agent_conversation_display_cache', {
  conversationId: text('conversationId').notNull(),
  chunkIndex: integer('chunkIndex').notNull(),
  ledgerRevision: integer('ledgerRevision').notNull(),
  payloadJson: text('payloadJson').notNull(),
  rendererVersion: integer('rendererVersion').notNull(),
  updatedAt: text('updatedAt').notNull(),
}, (table) => [primaryKey({ columns: [table.conversationId, table.chunkIndex] })])

export const agentBranches = sqliteTable('agent_branches', {
  id: text('id').notNull().primaryKey(),
  conversationId: text('conversationId').notNull(),
  parentBranchId: text('parentBranchId'),
  forkedFromTurnId: text('forkedFromTurnId'),
  headSequence: integer('headSequence').notNull(),
  name: text('name').notNull(),
  reason: text('reason').notNull(),
  createdAt: text('createdAt').notNull(),
})

export const conversationSpeakers = sqliteTable('conversation_speakers', {
  id: text('id').notNull().primaryKey(),
  conversationId: text('conversationId').notNull(),
  sourceSpeakerId: text('sourceSpeakerId').notNull(),
  kind: text('kind').notNull(),
  displayName: text('displayName').notNull(),
  avatarAssetId: text('avatarAssetId').notNull(),
})

export const agentTurns = sqliteTable('agent_turns', {
  id: text('id').notNull().primaryKey(),
  conversationId: text('conversationId').notNull(),
  speakerId: text('speakerId').notNull(),
  sourceMessageId: text('sourceMessageId').notNull(),
  kind: text('kind').notNull(),
  provider: text('provider').notNull(),
  model: text('model').notNull(),
  createdAt: text('createdAt').notNull(),
  variableStateJson: text('variableStateJson').notNull(),
})

export const agentResponses = sqliteTable('agent_responses', {
  id: text('id').notNull().primaryKey(),
  conversationId: text('conversationId').notNull(),
  turnId: text('turnId').notNull(),
  responseIndex: integer('responseIndex').notNull(),
  speakerId: text('speakerId').notNull(),
  sourceMessageId: text('sourceMessageId').notNull(),
  status: text('status').notNull(),
  provider: text('provider').notNull(),
  model: text('model').notNull(),
  createdAt: text('createdAt').notNull(),
  variableStateJson: text('variableStateJson').notNull(),
  runtimeThreadId: text('runtimeThreadId').notNull(),
  runtimeTurnId: text('runtimeTurnId').notNull(),
  turnStartedAtMillis: integer('turnStartedAtMillis').notNull(),
  turnCompletedAtMillis: integer('turnCompletedAtMillis'),
})

export const agentBranchTurns = sqliteTable('agent_branch_turns', {
  branchId: text('branchId').notNull(),
  sequence: integer('sequence').notNull(),
  turnId: text('turnId').notNull(),
}, (table) => [primaryKey({ columns: [table.branchId, table.sequence] })])

export const agentContentParts = sqliteTable('agent_content_parts', {
  conversationId: text('conversationId').notNull(),
  ownerType: text('ownerType').notNull(),
  ownerId: text('ownerId').notNull(),
  partIndex: integer('partIndex').notNull(),
  kind: text('kind').notNull(),
  text: text('text').notNull(),
  payloadJson: text('payloadJson').notNull(),
  chunkIndex: integer('chunkIndex').notNull(),
}, (table) => [primaryKey({ columns: [table.ownerType, table.ownerId, table.partIndex, table.chunkIndex] })])

export const generationAttempts = sqliteTable('generation_attempts', {
  id: text('id').notNull().primaryKey(),
  conversationId: text('conversationId').notNull(),
  kind: text('kind').notNull(),
  ownerId: text('ownerId').notNull(),
  parentAttemptId: text('parentAttemptId'),
  outputMessageId: text('outputMessageId').notNull(),
  attemptNumber: integer('attemptNumber').notNull(),
  state: text('state').notNull(),
  createdAtMillis: integer('createdAtMillis').notNull(),
  startedAtMillis: integer('startedAtMillis'),
  finishedAtMillis: integer('finishedAtMillis'),
  errorMessage: text('errorMessage').notNull(),
  outputPath: text('outputPath').notNull(),
  supersededByAttemptId: text('supersededByAttemptId'),
})

export const settingLibraries = sqliteTable('setting_libraries', {
  characterId: text('characterId').notNull().primaryKey(),
  name: text('name').notNull(),
  activeVersionId: text('activeVersionId').notNull(),
  listAllExpanded: integer('listAllExpanded').notNull(),
  expandedGroupIdsJson: text('expandedGroupIdsJson').notNull(),
  promptPositionsJson: text('promptPositionsJson').notNull(),
  updatedAt: text('updatedAt').notNull(),
})

export const settingEntryContents = sqliteTable('setting_entry_contents', {
  characterId: text('characterId').notNull(),
  entryId: text('entryId').notNull(),
  revisionId: text('revisionId').notNull(),
  payloadJson: text('payloadJson').notNull(),
}, (table) => [primaryKey({ columns: [table.characterId, table.entryId, table.revisionId] })])

export const settingLibraryEntryLinks = sqliteTable('setting_library_entry_links', {
  characterId: text('characterId').notNull(),
  entryId: text('entryId').notNull(),
  sortIndex: integer('sortIndex').notNull(),
  revisionId: text('revisionId').notNull(),
}, (table) => [primaryKey({ columns: [table.characterId, table.entryId] })])

export const settingLibraryGroups = sqliteTable('setting_library_groups', {
  characterId: text('characterId').notNull(),
  groupId: text('groupId').notNull(),
  sortIndex: integer('sortIndex').notNull(),
  payloadJson: text('payloadJson').notNull(),
}, (table) => [primaryKey({ columns: [table.characterId, table.groupId] })])

export const settingLibraryVersions = sqliteTable('setting_library_versions', {
  characterId: text('characterId').notNull(),
  versionId: text('versionId').notNull(),
  sortIndex: integer('sortIndex').notNull(),
  name: text('name').notNull(),
  listAllExpanded: integer('listAllExpanded').notNull(),
  expandedGroupIdsJson: text('expandedGroupIdsJson').notNull(),
  promptPositionsJson: text('promptPositionsJson').notNull(),
  createdAt: text('createdAt').notNull(),
  updatedAt: text('updatedAt').notNull(),
}, (table) => [primaryKey({ columns: [table.characterId, table.versionId] })])

export const settingLibraryVersionEntryLinks = sqliteTable('setting_library_version_entry_links', {
  characterId: text('characterId').notNull(),
  versionId: text('versionId').notNull(),
  entryId: text('entryId').notNull(),
  sortIndex: integer('sortIndex').notNull(),
  revisionId: text('revisionId').notNull(),
}, (table) => [primaryKey({ columns: [table.characterId, table.versionId, table.entryId] })])

export const settingLibraryVersionGroups = sqliteTable('setting_library_version_groups', {
  characterId: text('characterId').notNull(),
  versionId: text('versionId').notNull(),
  groupId: text('groupId').notNull(),
  sortIndex: integer('sortIndex').notNull(),
  payloadJson: text('payloadJson').notNull(),
}, (table) => [primaryKey({ columns: [table.characterId, table.versionId, table.groupId] })])

export const conversationSettingChanges = sqliteTable('conversation_setting_changes', {
  sessionId: text('sessionId').notNull(),
  targetType: text('targetType').notNull(),
  targetId: text('targetId').notNull(),
  operation: text('operation').notNull(),
  payloadJson: text('payloadJson').notNull(),
  updatedAt: text('updatedAt').notNull(),
}, (table) => [primaryKey({ columns: [table.sessionId, table.targetType, table.targetId] })])

export const roleplayRichHeights = sqliteTable('roleplay_rich_heights', {
  sessionId: text('sessionId').notNull(),
  messageId: text('messageId').notNull(),
  contentRevision: text('contentRevision').notNull(),
  rootIndex: integer('rootIndex').notNull(),
  viewportWidthPx: integer('viewportWidthPx').notNull(),
  heightPx: integer('heightPx').notNull(),
  measuredAtEpochMs: integer('measuredAtEpochMs').notNull(),
}, (table) => [primaryKey({ columns: [table.sessionId, table.messageId, table.contentRevision, table.rootIndex, table.viewportWidthPx] })])

export const agentPresetState = sqliteTable('agent_preset_state', {
  singletonId: integer('singletonId').notNull().primaryKey(),
  activePresetId: text('activePresetId').notNull(),
})

export const agentPresetLibraryGroups = sqliteTable('agent_preset_library_groups', {
  id: text('id').notNull().primaryKey(),
  name: text('name').notNull(),
  sortIndex: integer('sortIndex').notNull(),
})

export const agentPresets = sqliteTable('agent_presets', {
  id: text('id').notNull().primaryKey(),
  name: text('name').notNull(),
  modelFamily: text('modelFamily').notNull(),
  modelTagsJson: text('modelTagsJson').notNull().default(sql.raw("'[]'")),
  libraryGroupId: text('libraryGroupId').notNull().default(sql.raw("''")),
  activeVersionId: text('activeVersionId').notNull().default(sql.raw("''")),
  authorName: text('authorName').notNull().default(sql.raw("''")),
  authorAvatarPath: text('authorAvatarPath').notNull().default(sql.raw("''")),
  usageInstructions: text('usageInstructions').notNull().default(sql.raw("''")),
  sortIndex: integer('sortIndex').notNull(),
  expandedGroupIdsJson: text('expandedGroupIdsJson').notNull(),
})

export const agentPresetContents = sqliteTable('agent_preset_contents', {
  presetId: text('presetId').notNull(),
  kind: text('kind').notNull(),
  content: text('content').notNull(),
}, (table) => [primaryKey({ columns: [table.presetId, table.kind] })])

export const agentPresetEntries = sqliteTable('agent_preset_entries', {
  presetId: text('presetId').notNull(),
  entryId: text('entryId').notNull(),
  sortIndex: integer('sortIndex').notNull(),
  payloadJson: text('payloadJson').notNull(),
}, (table) => [primaryKey({ columns: [table.presetId, table.entryId] })])

export const agentPresetGroups = sqliteTable('agent_preset_groups', {
  presetId: text('presetId').notNull(),
  groupId: text('groupId').notNull(),
  sortIndex: integer('sortIndex').notNull(),
  payloadJson: text('payloadJson').notNull(),
}, (table) => [primaryKey({ columns: [table.presetId, table.groupId] })])

export const agentPresetVersions = sqliteTable('agent_preset_versions', {
  presetId: text('presetId').notNull(),
  versionId: text('versionId').notNull(),
  versionNumber: integer('versionNumber').notNull(),
  name: text('name').notNull().default(sql.raw("''")),
  createdAtEpochMs: integer('createdAtEpochMs').notNull(),
  expandedGroupIdsJson: text('expandedGroupIdsJson').notNull(),
}, (table) => [primaryKey({ columns: [table.presetId, table.versionId] })])

export const agentPresetVersionContents = sqliteTable('agent_preset_version_contents', {
  presetId: text('presetId').notNull(),
  versionId: text('versionId').notNull(),
  kind: text('kind').notNull(),
  content: text('content').notNull(),
}, (table) => [primaryKey({ columns: [table.presetId, table.versionId, table.kind] })])

export const agentPresetVersionEntries = sqliteTable('agent_preset_version_entries', {
  presetId: text('presetId').notNull(),
  versionId: text('versionId').notNull(),
  entryId: text('entryId').notNull(),
  sortIndex: integer('sortIndex').notNull(),
  payloadJson: text('payloadJson').notNull(),
}, (table) => [primaryKey({ columns: [table.presetId, table.versionId, table.entryId] })])

export const agentPresetVersionGroups = sqliteTable('agent_preset_version_groups', {
  presetId: text('presetId').notNull(),
  versionId: text('versionId').notNull(),
  groupId: text('groupId').notNull(),
  sortIndex: integer('sortIndex').notNull(),
  payloadJson: text('payloadJson').notNull(),
}, (table) => [primaryKey({ columns: [table.presetId, table.versionId, table.groupId] })])

export const commonTables = { chatSessions, chatSessionCharacterSnapshots, chatSessionModelSettings, chatSessionVariableStates, characters, characterTextContents, characterMeta, userProfile, modelConfigs, modelConfigMeta, variableConfigs, variableConfigVersions, variableConfigVersionContents, variableConfigObjects, variableConfigVariables, globalRegexRules, characterRegexRules, regexEnablementVersions, regexState, globalToolConfig, frontendProjects, characterFrontendSettings, cleanupOperations, agentConversations, agentConversationDisplayCache, agentBranches, conversationSpeakers, agentTurns, agentResponses, agentBranchTurns, agentContentParts, generationAttempts, settingLibraries, settingEntryContents, settingLibraryEntryLinks, settingLibraryGroups, settingLibraryVersions, settingLibraryVersionEntryLinks, settingLibraryVersionGroups, conversationSettingChanges, roleplayRichHeights, agentPresetState, agentPresetLibraryGroups, agentPresets, agentPresetContents, agentPresetEntries, agentPresetGroups, agentPresetVersions, agentPresetVersionContents, agentPresetVersionEntries, agentPresetVersionGroups }
